clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: toolkit
  
pipeline:
  test-dc-database-operations:
    image: fpfis/drone-plugin-deploy
    secrets:
      - source: ${SITE_SALTAPI_URL}
        target: saltapi_url
      - source: ${SITE_SALTAPI_USER}
        target: saltapi_user
      - source: ${SITE_SALTAPI_PASS}
        target: saltapi_pass
      - source: saltapi_eauth
        target: saltapi_eauth
      - source: asda_url
        target: asda_url
      - source: asda_aws_url
        target: asda_aws_url
    location: DC
    drone_repo_name: digit-platform-dc-test
    action: db_refresh
    pull: true
    environment:
      - DRONE_DEPLOY_TO=acc
