clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: plugins/git
    when:
      event: [ deployment ]


matrix:
  - MATRIX_VAR: 'matrix01'
  - MATRIX_VAR: 'matrix02'
  - MATRIX_VAR: 'matrix03'
      
workspace:
  base: /test
  path: toolkit
  
pipeline:
  test-01:
    image: ubuntu
    commands:
      - echo $MATRIX_VAR
      - for i in $(seq 1 3600);do echo "$i";sleep 1;done
