clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: plugins/git
    when:
      event: [ deployment ]

pipeline:
  test:
    image: registry.fpfis.eu/drone-plugins/docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "hello"
      - docker --version
      - docker -H unix:///var/run/docker.sock version
      - docker build .
    environment:
      - DOCUMENT_ROOT=/test/toolkit
      - DOCKER_BUILDKIT=1

  publish-base:
    image: registry.fpfis.eu/drone-plugins/docker
    privileged: true
    tags:
      - trololol
    registry: registry.fpfis.eu
    dockerfile: Dockerfile
    debug: true
    environment:
      - DOCUMENT_ROOT=/test/toolkit
      - DOCKER_BUILDKIT=1



