clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: plugins/git
    when:
      event: [ deployment ]

pipeline:
  test:
    image: registry.fpfis.eu/drone-plugins/docker
    commands:
      - echo "hello"
      - docker --version

  publish-base:
    image: registry.fpfis.eu/drone-plugins/docker
    privileged: true
    tags:
      - trololol
    registry: registry.fpfis.eu
    dockerfile: Dockerfile
    debug: true



