clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: toolkit
  
pipeline:
  test-docker-gilabs-access:
    group: test
    image: registry.fpfis.eu/drone-plugins/deploy:latest
    secrets: [ saltapi_url, saltapi_user, saltapi_pass, saltapi_eauth, asda_url, asda_aws_url ]
    location: DC
    drone_repo_name: digit-platform-dc-test
    action: db_refresh
    pull: true
    environment:
      - DRONE_DEPLOY_TO=acc

  test-docker-hub-access:
    group: test
    image: gervase/test:first
    commands: 
      - ls -la

  publish-docker-to-gitlab:
    image: plugins/docker
    repo: registry.fpfis.eu/gervasek/test-pipeline
    tags:
      - drone-$DRONE_COMMIT_SHA
    registry: registry.fpfis.eu
    dockerfile: Dockerfile
