clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: plugins/git
    when:
      event: [ deployment ]

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:8.3-ci
    environment: &env
      - DOCUMENT_ROOT=/test/toolkit

pipeline:
  project-install:
    image: registry.fpfis.eu/fpfis/httpd-php:8.3-ci
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    environment: *env
    commands:
      - /scripts/run.sh echo "Container ready"
      - composer self-update --${COMPOSER_VERSION=2}
      - composer install --ansi --no-progress --ignore-platform-reqs
      - curl http://web:8080/imap-status.php
      - php imap-status.php
      - ./vendor/bin/run toolkit:install-dependencies
      - curl http://web:8080/imap-status.php
      - php imap-status.php

  test1:
    image: registry.fpfis.eu/fpfis/httpd-php:8.3-ci
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    environment: *env
    commands:
      - curl http://web:8080/imap-status.php
      - php imap-status.php



