clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: toolkit
  
pipeline:
  asda:
    image: ubuntu
    commands:
      - for i in $(seq 1 20);do echo -n ".";sleep 1;done
