clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: plugins/git
    when:
      event: [ deployment ]


matrix:
  BUILD_INFORMATION_MATRIX:
    - 'matrix01'
  HOUSING_DESTINATION_MATRIX:
    - 'matrix02'
  DEPLOY_PLUGIN_MATRIX:
    - 'matrix03'
      
workspace:
  base: /test
  path: toolkit
  
pipeline:
  test-01:
    secrets: [ secret1 ]
    image: ubuntu
    koinkoin: True
    commands:
      - env
      
  test-20-sec:
    image: ubuntu
    commands:
      - for i in $(seq 1 20);do echo "$i";sleep 1;done
