clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: toolkit
  
pipeline:
  test-20-sec:
    group: koin
    image: ubuntu
    commands:
      - for i in $(seq 1 20);do echo "$i";sleep 1;done

  test-koin:
    image: fpfis/httpd-php-dev
    group: koin
    secrets: [ PHP_VERSION ]    
    commands:
      - php --version
      - echo ${KOIN}
      
  test-koin2:
    image: fpfis/httpd-php-dev
    group: koin
    secrets: [ PHP_VERSION ]    
    commands:
      - php --version
      - echo ${KOIN}
